/* Skillora Week 8 — final integration / UX layer */
(function(){
'use strict';
const KEY='skillora_w8_user', NOTIFY='skillora_w8_notifications';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function getUser(){try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}}
function setUser(u){localStorage.setItem(KEY,JSON.stringify(u));updateSession()}
function getNotifications(){try{return JSON.parse(localStorage.getItem(NOTIFY))||[]}catch{return[]}}
function seedNotifications(){if(!localStorage.getItem(NOTIFY))localStorage.setItem(NOTIFY,JSON.stringify([
{id:'n1',title:'Welcome to Skillora Week 8',text:'Your final marketplace workspace is ready.',time:'Just now',read:false},
{id:'n2',title:'Proposal update',text:'A client viewed your latest proposal.',time:'2h ago',read:false},
{id:'n3',title:'Project milestone',text:'A project milestone is ready for review.',time:'Yesterday',read:false}
]));}
function unread(){return getNotifications().filter(n=>!n.read).length}
function toast(msg){let t=$('#w8Toast');if(!t){t=document.createElement('div');t.id='w8Toast';t.className='w8-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__w8t);window.__w8t=setTimeout(()=>t.classList.remove('show'),2400)}
function authModal(mode='login'){
 let b=$('#w8Auth');if(!b){b=document.createElement('div');b.id='w8Auth';b.className='w8-auth-backdrop';b.innerHTML=`<div class="w8-auth-card" role="dialog" aria-modal="true" aria-labelledby="w8AuthTitle"><div class="w8-auth-head"><div><h2 id="w8AuthTitle">Welcome back</h2><p id="w8AuthSub">Sign in to continue your work.</p></div><button class="w8-close" aria-label="Close">×</button></div><div class="w8-tabs"><button data-mode="login">Login</button><button data-mode="register">Register</button></div><form class="w8-form" id="w8AuthForm"><div class="w8-field"><label>Name</label><input id="w8Name" autocomplete="name" placeholder="Your name"></div><div class="w8-field"><label>Email</label><input id="w8Email" type="email" required autocomplete="email" placeholder="you@example.com"></div><div class="w8-field"><label>Password</label><input id="w8Password" type="password" minlength="6" required autocomplete="current-password" placeholder="At least 6 characters"></div><div class="w8-field" id="w8RoleField"><label>Account type</label><select id="w8Role"><option value="client">Client</option><option value="freelancer">Freelancer</option></select></div><div class="w8-error" id="w8AuthError"></div><button class="w8-primary" type="submit" id="w8AuthSubmit">Login to Skillora</button></form></div>`;document.body.appendChild(b);
  $('.w8-close',b).onclick=()=>b.classList.remove('open'); b.addEventListener('click',e=>{if(e.target===b)b.classList.remove('open')});
  $$('[data-mode]',b).forEach(x=>x.onclick=()=>authModal(x.dataset.mode));
  $('#w8AuthForm',b).onsubmit=e=>{e.preventDefault();const register=b.dataset.mode==='register',email=$('#w8Email',b).value.trim(),pass=$('#w8Password',b).value.trim(),name=$('#w8Name',b).value.trim()||email.split('@')[0];if(pass.length<6){$('#w8AuthError',b).textContent='Password must contain at least 6 characters.';return}if(register&&!name){$('#w8AuthError',b).textContent='Please enter your name.';return}setUser({name,email,role:register?$('#w8Role',b).value:(getUser()?.role||'client'),avatar:`https://i.pravatar.cc/100?u=${encodeURIComponent(email)}`});b.classList.remove('open');toast(register?'Account created — welcome to Skillora!':'Signed in successfully.');};
 }
 b.dataset.mode=mode;const reg=mode==='register';$('#w8AuthTitle',b).textContent=reg?'Create your Skillora account':'Welcome back';$('#w8AuthSub',b).textContent=reg?'Start managing services, projects and clients.':'Sign in to continue your work.';$('#w8Name',b).style.display=reg?'block':'none';$('#w8RoleField',b).style.display=reg?'grid':'none';$('#w8AuthSubmit',b).textContent=reg?'Create account':'Login to Skillora';$('#w8AuthError',b).textContent='';$$('[data-mode]',b).forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));b.classList.add('open');setTimeout(()=>$('#w8Email',b).focus(),50);
}
function updateSession(){const user=getUser();$$('.w8-session').forEach(x=>x.remove());const nav=$('.nav-actions');if(!nav)return;const old=$('.login-btn',nav);if(old)old.style.display=user?'none':'';const reg=$('.register-btn',nav);if(reg)reg.style.display=user?'none':'';if(user){const wrap=document.createElement('div');wrap.className='w8-session w8-user-menu';wrap.innerHTML=`<button class="w8-user-trigger"><img class="w8-avatar" src="${esc(user.avatar)}" alt=""><span>${esc(user.name)}</span><i class="fa-solid fa-chevron-down"></i></button><div class="w8-user-pop"><small>${esc(user.email)} · ${esc(user.role)}</small><a href="profile.html">My Profile</a><a href="advanced-dashboard.html">Dashboard</a><a href="messages.html">Messages <span class="w8-notification-dot">${unread()}</span></a><button id="w8Logout">Sign out</button></div>`;nav.prepend(wrap);$('.w8-user-trigger',wrap).onclick=()=>$('.w8-user-pop',wrap).classList.toggle('open');$('#w8Logout',wrap).onclick=()=>{localStorage.removeItem(KEY);toast('Signed out.');setTimeout(()=>location.reload(),500)}}}
function addGlobalNav(){seedNotifications();const login=$('#loginBtn'),register=$('#registerBtn'),ml=$('#mobileLogin'),mr=$('#mobileRegister');if(login)login.onclick=e=>{e.preventDefault();authModal('login')};if(register)register.onclick=e=>{e.preventDefault();authModal('register')};if(ml)ml.onclick=e=>{e.preventDefault();authModal('login')};if(mr)mr.onclick=e=>{e.preventDefault();authModal('register')};
 // For pages without the homepage auth controls, add a compact session button.
 if(!$('.nav-actions'))return;updateSession();
}
function addFooter(){if($('footer')||$('.w8-footer'))return;const f=document.createElement('footer');f.className='w8-footer';f.innerHTML=`<div class="w8-footer-inner"><div><strong>Skillora</strong><p>Freelancing, simplified — discover talent, manage projects and grow your work.</p></div><div class="w8-footer-links"><a href="index.html">Home</a><a href="marketplace.html">Marketplace</a><a href="find-jobs.html">Jobs</a><a href="messages.html">Messages</a><a href="reviews.html">Reviews</a><a href="advanced-dashboard.html">Dashboard</a></div><div><span class="w8-inline-status"><i class="fa-solid fa-circle-check"></i> Week 8 Final</span></div></div>`;document.body.appendChild(f)}
function addUtilities(){const skip=document.createElement('a');skip.href='#main';skip.className='w8-skip';skip.textContent='Skip to content';document.body.prepend(skip);const bar=document.createElement('div');bar.className='w8-loading-bar';document.body.prepend(bar);bar.style.width='65%';setTimeout(()=>bar.style.width='100%',80);setTimeout(()=>bar.remove(),450);const top=document.createElement('button');top.className='w8-backtop';top.innerHTML='<i class="fa-solid fa-arrow-up"></i>';top.setAttribute('aria-label','Back to top');document.body.appendChild(top);window.addEventListener('scroll',()=>top.classList.toggle('show',scrollY>500),{passive:true});top.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('button,a,input,select,textarea').forEach(el=>el.classList.add('w8-focus-visible'));}
function improveForms(){ $$('form').forEach(form=>{form.addEventListener('invalid',()=>toast('Please check the highlighted fields.'),true);form.addEventListener('submit',e=>{if(!form.checkValidity())return;const btn=form.querySelector('button[type="submit"]');if(btn&&!btn.dataset.w8){btn.dataset.w8='1';const old=btn.innerHTML;btn.disabled=true;btn.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Saving…';setTimeout(()=>{btn.disabled=false;btn.innerHTML=old;delete btn.dataset.w8},900)}})}); }
function addReviewShortcut(){if(location.pathname.endsWith('project-details.html'))return;const main=$('main');if(!main||$('.w8-review-cta'))return;}
document.addEventListener('DOMContentLoaded',()=>{addGlobalNav();addFooter();addUtilities();improveForms();if(!$('#main')){const first=$('main, .hero, section');if(first)first.id='main'} });
window.SkilloraW8={auth:authModal,getUser,setUser,toast,getNotifications,seedNotifications,unread};
})();
